apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpdserver
  name: httpdserver
spec:
  volumes:
    - name: httpd-pv-storage
      persistentVolumeClaim:
        claimName: httpd-pv-claim
  containers:
  - image: httpd
    name: httpdserver
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
        - mountPath: "/var/www/html"
          name: httpd-pv-storage
