apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: khairane/knote:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: knote-vars
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: knote-service
spec:
  ports:
    - name: http 
      port: 80
      targetPort: 8080
  selector:
    app: knote
  type: NodePort

